# apiVersion: v1
# kind: Pod
# metadata:
#   name: my-secret-pod
#   namespace: secret-app
# spec:
#   serviceAccountName: mypodserviceaccount
#   containers:
#     - name: mypod
#       image: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
#       resources:
#         requests:
#           cpu: 100m
#       volumeMounts:
#         - name: mysecret
#           mountPath: "/var/secrets"
#       terminationMessagePath: /dev/termination-log
#       terminationMessagePolicy: File
#       imagePullPolicy: IfNotPresent
#       securityContext:
#         allowPrivilegeEscalation: false
#         readOnlyRootFilesystem: true
#       stdin: true
#       stdinOnce: true
#       tty: true
#   volumes:
#     - name: mysecret
#       csi:
#         readOnly: true
#         driver: secrets-store.csi.k8s.io
#         volumeAttributes:
#           secretProviderClass: "app-secrets"
#   securityContext:
#     fsGroup: 1234
#     runAsNonRoot: true
#     runAsUser: 1234
