
stages:
  - validate

validate:
  stage: validate
  image:
    name: gcr.io/config-management-release/nomos:stable
    entrypoint:
      - ""                          # Override default entrypoint.
  script:
    - ls
    - nomos vet
