apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedRepos
metadata:
  name: allowed-repos
  annotations:
    configmanagement.gke.io/cluster-selector: selector-env-prod  
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces: ["microservices-demo"]
  parameters:
    repos:
      - "gcr.io"
      - "gke.gcr.io"
