apiVersion: configsync.gke.io/v1alpha1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: microservices-demo
spec:
  git:
   repo: git@github.com:cartyc/microservices-demo.git
   branch: master
   dir: "release"
   auth: ssh
   secretRef:
     name: test
