apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: microservices-demo-bad
spec:
  podSelector: {}
  ingress:
  - ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443