# Source: secrets-store-csi-driver/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretproviderclasses-role
rules:
  - resources:
      - events
    apiGroups:
      - ""
    verbs:
      - create
      - patch
  - resources:
      - pods
    apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
  - resources:
      - secretproviderclasses
    apiGroups:
      - secrets-store.csi.x-k8s.io
    verbs:
      - get
      - list
      - watch
  - resources:
      - secretproviderclasspodstatuses
    apiGroups:
      - secrets-store.csi.x-k8s.io
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - resources:
      - secretproviderclasspodstatuses/status
    apiGroups:
      - secrets-store.csi.x-k8s.io
    verbs:
      - get
      - patch
      - update
---
# Source: secrets-store-csi-driver/templates/role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secretproviderclasses-rolebinding
roleRef:
  name: secretproviderclasses-role
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: secrets-store-csi-driver
    namespace: csi-driver
    kind: ServiceAccount
---
# Source: secrets-store-csi-driver/templates/csidriver.yaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: secrets-store.csi.k8s.io
spec:
  attachRequired: false
  podInfoOnMount: true
  # Added in Kubernetes 1.16 with default mode of Persistent. Secrets store csi driver needs Ephermeral to be set.
  volumeLifecycleModes:
    - Ephemeral
---
# Source: secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-secrets-store-secrets-store-csi-driver-upgrade-crds
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: "csi-secrets-store"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "secrets-store-csi-driver"
    app.kubernetes.io/version: "0.2.0"
    helm.sh/chart: "secrets-store-csi-driver-0.2.0"
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: "hook-succeeded,before-hook-creation"
    helm.sh/hook-weight: "1"
rules:
  - resources: ["customresourcedefinitions"]
    apiGroups: ["apiextensions.k8s.io"]
    verbs: ["get", "create", "update", "patch"]
---
# Source: secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-secrets-store-secrets-store-csi-driver-keep-crds
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: "csi-secrets-store"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "secrets-store-csi-driver"
    app.kubernetes.io/version: "0.2.0"
    helm.sh/chart: "secrets-store-csi-driver-0.2.0"
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: "hook-succeeded,before-hook-creation"
    helm.sh/hook-weight: "2"
rules:
  - resources: ["customresourcedefinitions"]
    apiGroups: ["apiextensions.k8s.io"]
    verbs: ["get", "patch"]
---
# Source: secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-secrets-store-secrets-store-csi-driver-upgrade-crds
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: "csi-secrets-store"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "secrets-store-csi-driver"
    app.kubernetes.io/version: "0.2.0"
    helm.sh/chart: "secrets-store-csi-driver-0.2.0"
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: "hook-succeeded,before-hook-creation"
    helm.sh/hook-weight: "1"
roleRef:
  name: csi-secrets-store-secrets-store-csi-driver-upgrade-crds
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: csi-secrets-store-secrets-store-csi-driver-upgrade-crds
    namespace: csi-driver
    kind: ServiceAccount
---
# Source: secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-secrets-store-secrets-store-csi-driver-keep-crds
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: "csi-secrets-store"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "secrets-store-csi-driver"
    app.kubernetes.io/version: "0.2.0"
    helm.sh/chart: "secrets-store-csi-driver-0.2.0"
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: "hook-succeeded,before-hook-creation"
    helm.sh/hook-weight: "2"
roleRef:
  name: csi-secrets-store-secrets-store-csi-driver-keep-crds
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: csi-secrets-store-secrets-store-csi-driver-keep-crds
    namespace: csi-driver
    kind: ServiceAccount
