apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-store-csi-driver-provider-gcp-rolebinding
roleRef:
  name: secrets-store-csi-driver-provider-gcp-role
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: secrets-store-csi-driver-provider-gcp
    namespace: csi-driver
    kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-store-csi-driver-provider-gcp-role
rules:
  - resources:
      - serviceaccounts/token
    apiGroups:
      - ""
    verbs:
      - create
  - resources:
      - serviceaccounts
    apiGroups:
      - ""
    verbs:
      - get
